fix /tmp/np issue with default hook service start with custom function

diff --git a/deploy/hooks_conf_only/post-restore-code b/deploy/hooks_conf_only/post-restore-code
--- a/deploy/hooks_conf_only/post-restore-code
+++ b/deploy/hooks_conf_only/post-restore-code
@@ -1,5 +1,4 @@
 #!/bin/bash
-
 # variables set here:
 #   $TARGET: name of the symbolic remote host key (see remote_hosts
 #            section in config file)
@@ -14,6 +13,15 @@ green='\e[0;32m'
 red='\e[0;31m'
 yellow='\e[1;33m'
 NC='\e[0m' # No Color
+
+start_sphinx() {
+    # since systemctl can fail and the service can still run we have to check the success of it with searchd
+    sudo -u root systemctl start sphinxsearch || { echo "systemctl start was not successful, checking searchd --status instead ..."; }
+    wait 1
+    searchd --status
+    return $?
+}
+
 
 if [ "$*" = "clean_index" ]; then
     echo "executing $0 $*"
@@ -83,7 +91,7 @@ if ! searchd --status > /dev/null
 then
     echo -e "    ${red}WARNING: service was not running${NC}"
     echo "starting sphinx service with old configuration ..."
-    sudo -u root systemctl start sphinxsearch
+    start_sphinx
 fi
 
 echo "copy files preserving timestamp ..."
@@ -133,9 +141,9 @@ else
     echo "trying to load new sphinx config ..."
     # we need both stop scripts because systemctl is not always working...
     sudo -u root systemctl stop sphinxsearch
-    sudo -u sphinxsearch -s searchd --stop
+    sudo -u sphinxsearch -s searchd --stopwait
     sleep 5
-    sudo -u root systemctl start sphinxsearch
+    start_sphinx
 fi
 
 COUNTER=1
@@ -156,7 +164,8 @@ do
         echo -e "${red}service not running, try $COUNTER of $WAITFORSPHINX to start service ...${NC}"
     fi
     echo "    starting sphinx service with new config ..."
-    sudo -u root systemctl start sphinxsearch
+    start_sphinx
+
     COUNTER=$(($COUNTER +1))
     if test $COUNTER -gt $WAITFORSPHINX
     then
@@ -165,7 +174,7 @@ do
         if [ -f "/etc/sphinxsearch/sphinx.conf.backup" ]; then
             mv /etc/sphinxsearch/sphinx.conf.backup /etc/sphinxsearch/sphinx.conf
             echo "    starting sphinx service with old config ..."
-            sudo -u root systemctl start sphinxsearch
+            start_sphinx
         else
             echo -e "${red}WARNING: no valid sphinx configuration available. SERVICE NOT RUNNING${NC}"
             exit 1
